repos:
- hooks:
  - entry: bash -c "uv export --format requirements-txt --no-hashes --output-file
      requirements.txt --no-dev && uv export > requirements-dev.txt && git add requirements.txt
      requirements-dev.txt"
    files: pyproject.toml
    id: export-requirements
    language: system
    name: Export requirements files
    pass_filenames: false
    stages:
    - pre-commit
  repo: local
- hooks:
  - args:
    - --fix
    id: ruff
    stages:
    - pre-commit
    verbose: true
  - id: ruff-format
    stages:
    - pre-commit
    verbose: true
  repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.8.3
